# Generated by Django 2.2.4 on 2019-09-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='nickname',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
