# Generated by Django 2.2.4 on 2019-09-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0003_auto_20190929_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificuser',
            old_name='email_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='specificuser',
            old_name='first_name',
            new_name='email',
        ),
    ]
