# Generated by Django 2.2.4 on 2019-09-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0004_auto_20190929_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificuser',
            old_name='Name',
            new_name='start_loc',
        ),
        migrations.RemoveField(
            model_name='specificuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='specificuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='specificuser',
            name='username',
        ),
    ]
