# Generated by Django 2.2.4 on 2019-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0005_auto_20190929_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='from_Baramati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_loc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='from_Malegaon_College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_loc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='from_MalegaonBK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_loc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='from_Shardanagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_loc', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='specificUser',
        ),
    ]
