# Generated by Django 2.2.4 on 2019-10-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0006_auto_20190929_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
