# Generated by Django 2.2.4 on 2019-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
